namespace SnapshotExpert.Generator;

/// <summary>
/// Members marked with this attribute will be ignored
/// by snapshot serializers generated by <see cref="SerializerGenerator"/>.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
public class TransientAttribute : Attribute
{
}